# Generated by Django 4.2.27 on 2026-01-05 02:57

from decimal import Decimal
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nivel', models.CharField(choices=[('administrador', 'Administrador'), ('gerente', 'Gerente'), ('corretor', 'Corretor')], default='corretor', max_length=20, verbose_name='Nível de Acesso')),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('creci', models.CharField(blank=True, max_length=20, null=True, verbose_name='CRECI')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='usuarios/', verbose_name='Foto')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('rg', models.CharField(max_length=20, verbose_name='RG')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('estado_civil', models.CharField(choices=[('solteiro', 'Solteiro(a)'), ('casado', 'Casado(a)'), ('divorciado', 'Divorciado(a)'), ('viuvo', 'Viúvo(a)'), ('uniao_estavel', 'União Estável')], max_length=20, verbose_name='Estado Civil')),
                ('profissao', models.CharField(max_length=100, verbose_name='Profissão')),
                ('renda_mensal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Renda Mensal')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('endereco', models.TextField(verbose_name='Endereço')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=2, verbose_name='Estado')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('nome_conjuge', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do Cônjuge')),
                ('cpf_conjuge', models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF do Cônjuge')),
                ('rg_conjuge', models.CharField(blank=True, max_length=20, null=True, verbose_name='RG do Cônjuge')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('corretor_cadastro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_cadastrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=50, unique=True)),
                ('valor', models.TextField()),
                ('descricao', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Configuração',
                'verbose_name_plural': 'Configurações',
            },
        ),
        migrations.CreateModel(
            name='Construtora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('endereco', models.TextField(verbose_name='Endereço')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Construtora',
                'verbose_name_plural': 'Construtoras',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contrato', models.CharField(max_length=20, unique=True, verbose_name='Número do Contrato')),
                ('registro_imovel', models.CharField(blank=True, max_length=100, null=True, verbose_name='Registro do Imóvel')),
                ('matricula', models.CharField(blank=True, max_length=50, null=True, verbose_name='Matrícula')),
                ('cartorio', models.CharField(blank=True, max_length=200, null=True, verbose_name='Cartório')),
                ('data_assinatura', models.DateField(verbose_name='Data de Assinatura')),
                ('data_vencimento_primeira_parcela', models.DateField(verbose_name='Vencimento 1ª Parcela')),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Empreendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('endereco', models.TextField(verbose_name='Endereço')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=2, verbose_name='Estado')),
                ('data_lancamento', models.DateField(verbose_name='Data de Lançamento')),
                ('data_entrega_prevista', models.DateField(verbose_name='Previsão de Entrega')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('percentual_corretor', models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=5, verbose_name='Comissão Corretor (%)')),
                ('percentual_gerente', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5, verbose_name='Comissão Gerente (%)')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('construtora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empreendimentos', to='contratus.construtora')),
            ],
            options={
                'verbose_name': 'Empreendimento',
                'verbose_name_plural': 'Empreendimentos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoUnidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Tipo')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Tipo de Unidade',
                'verbose_name_plural': 'Tipos de Unidade',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='UnidadeEmpreendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, verbose_name='Número/Identificação')),
                ('bloco', models.CharField(blank=True, max_length=50, null=True, verbose_name='Bloco/Torre')),
                ('andar', models.CharField(blank=True, max_length=10, null=True, verbose_name='Andar')),
                ('area_privativa', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Área Privativa (m²)')),
                ('quartos', models.IntegerField(verbose_name='Quartos')),
                ('suites', models.IntegerField(default=0, verbose_name='Suítes')),
                ('banheiros', models.IntegerField(verbose_name='Banheiros')),
                ('vagas_garagem', models.IntegerField(default=0, verbose_name='Vagas de Garagem')),
                ('valor_imovel', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor do Imóvel')),
                ('valor_engenharia', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor de Engenharia')),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('reservada', 'Reservada'), ('vendida', 'Vendida')], default='disponivel', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('empreendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='contratus.empreendimento')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unidades', to='contratus.tipounidade', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Unidade',
                'verbose_name_plural': 'Unidades',
                'ordering': ['empreendimento', 'numero'],
                'unique_together': {('empreendimento', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_proposta', models.CharField(max_length=20, unique=True, verbose_name='Número da Proposta')),
                ('valor_construtora', models.DecimalField(decimal_places=2, help_text='Valor que será pago à construtora', max_digits=12, verbose_name='Valor para Construtora (sem juros)')),
                ('valor_parcela_cliente', models.DecimalField(decimal_places=2, help_text='Informe o valor mensal que o cliente consegue pagar', max_digits=12, verbose_name='Valor Mensal que Cliente Pode Pagar')),
                ('valor_com_juros', models.DecimalField(decimal_places=2, help_text='Automático: Valor sem juros × 1,5', max_digits=12, verbose_name='Valor COM Juros (50%)')),
                ('quantidade_parcelas', models.IntegerField(help_text='Automático: Valor com juros ÷ Valor da parcela', verbose_name='Número de Parcelas')),
                ('valor_financiamento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Financiamento')),
                ('valor_subsidio', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Subsídio')),
                ('valor_fgts', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='FGTS')),
                ('total_aprovacao', models.DecimalField(decimal_places=2, help_text='Financiamento + Subsídio + FGTS', max_digits=12, verbose_name='Total da Aprovação')),
                ('valor_entrada', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Valor de Entrada')),
                ('status', models.CharField(choices=[('analise', 'Em Análise'), ('aprovada', 'Aprovada'), ('reprovada', 'Reprovada'), ('cancelada', 'Cancelada')], default='analise', max_length=20, verbose_name='Status')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contratus.cliente')),
                ('corretor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='propostas', to=settings.AUTH_USER_MODEL)),
                ('empreendimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contratus.empreendimento')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contratus.unidadeempreendimento')),
            ],
            options={
                'verbose_name': 'Proposta',
                'verbose_name_plural': 'Propostas',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.TextField()),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='contratus.contrato')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Contrato',
                'verbose_name_plural': 'Históricos de Contratos',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('ativa', models.BooleanField(default=True)),
                ('lider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipes_lideradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Equipe',
                'verbose_name_plural': 'Equipes',
            },
        ),
        migrations.AddField(
            model_name='contrato',
            name='proposta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='contrato', to='contratus.proposta'),
        ),
        migrations.CreateModel(
            name='Comissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('percentual', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('paga', 'Paga'), ('cancelada', 'Cancelada')], default='pendente', max_length=20)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratus.contrato')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comissão',
                'verbose_name_plural': 'Comissões',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='equipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membros', to='contratus.equipe'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='contratus_user_set', related_query_name='contratus_user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='contratus_user_set', related_query_name='contratus_user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
