# Generated by Django 4.2.27 on 2026-01-05 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('assinado', 'Assinado'), ('em_andamento', 'Em Andamento'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado'), ('distratado', 'Distratado')], default='ativo', max_length=20, verbose_name='Status'),
        ),
    ]
