# Generated by Django 4.2.27 on 2026-01-09 15:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratus', '0002_contrato_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nome_completo']},
        ),
        migrations.AlterModelOptions(
            name='construtora',
            options={'ordering': ['nome_fantasia'], 'verbose_name': 'Construtora', 'verbose_name_plural': 'Construtoras'},
        ),
        migrations.AlterModelOptions(
            name='empreendimento',
            options={'ordering': ['nome']},
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='cpf_conjuge',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='nome_conjuge',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='profissao',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='renda_mensal',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='rg_conjuge',
        ),
        migrations.RemoveField(
            model_name='construtora',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='construtora',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='empreendimento',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='empreendimento',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='empreendimento',
            name='percentual_corretor',
        ),
        migrations.RemoveField(
            model_name='empreendimento',
            name='percentual_gerente',
        ),
        migrations.AddField(
            model_name='cliente',
            name='bairro',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='complemento',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nome_completo',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='numero',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='origem',
            field=models.CharField(choices=[('site', 'Site'), ('indicacao', 'Indicação'), ('midia_social', 'Mídia Social'), ('evento', 'Evento'), ('plantao', 'Plantão'), ('outro', 'Outro')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='rua',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='construtora',
            name='ativa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='construtora',
            name='bairro',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='construtora',
            name='cep',
            field=models.CharField(default=24465540, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='construtora',
            name='cidade',
            field=models.CharField(default=11, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='construtora',
            name='complemento',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='construtora',
            name='estado',
            field=models.CharField(default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='construtora',
            name='nome_fantasia',
            field=models.CharField(default='', max_length=200, verbose_name='Nome Fantasia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='construtora',
            name='numero',
            field=models.CharField(default=12, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='construtora',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='construtora',
            name='razao_social',
            field=models.CharField(default='', max_length=200, verbose_name='Razão Social'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='construtora',
            name='responsavel_legal',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='construtora',
            name='rua',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empreendimento',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='empreendimento',
            name='bairro',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empreendimento',
            name='cep',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empreendimento',
            name='complemento',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='empreendimento',
            name='descricao_completa',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empreendimento',
            name='imagem_principal',
            field=models.ImageField(blank=True, null=True, upload_to='empreendimentos/'),
        ),
        migrations.AddField(
            model_name='empreendimento',
            name='numero',
            field=models.CharField(default=12, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empreendimento',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='empreendimento',
            name='rua',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empreendimento',
            name='status',
            field=models.CharField(choices=[('planejamento', 'Em Planejamento'), ('lancamento', 'Lançamento'), ('obras', 'Em Obras'), ('pronto', 'Pronto'), ('entregue', 'Entregue')], default='planejamento', max_length=20),
        ),
        migrations.AddField(
            model_name='empreendimento',
            name='taxa_corretagem_percentual',
            field=models.DecimalField(decimal_places=2, default=Decimal('4.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='empreendimento',
            name='tipo_imovel',
            field=models.CharField(choices=[('apartamento', 'Apartamento'), ('casa', 'Casa'), ('terreno', 'Terreno'), ('comercial', 'Comercial'), ('rural', 'Rural')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empreendimento',
            name='total_unidades',
            field=models.PositiveIntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empreendimento',
            name='unidades_disponiveis',
            field=models.PositiveIntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cep',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cidade',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='data_nascimento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='estado',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='estado_civil',
            field=models.CharField(choices=[('solteiro', 'Solteiro(a)'), ('casado', 'Casado(a)'), ('divorciado', 'Divorciado(a)'), ('viuvo', 'Viúvo(a)'), ('uniao_estavel', 'União Estável')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rg',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='construtora',
            name='cnpj',
            field=models.CharField(max_length=18, unique=True),
        ),
        migrations.AlterField(
            model_name='construtora',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='construtora',
            name='telefone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='empreendimento',
            name='cidade',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='empreendimento',
            name='data_entrega_prevista',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='empreendimento',
            name='data_lancamento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='empreendimento',
            name='estado',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='empreendimento',
            name='nome',
            field=models.CharField(max_length=200),
        ),
    ]
