# Generated by Django 4.2.27 on 2026-01-03 02:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratus', '0002_alter_cliente_id_alter_comissao_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empreendimento',
            name='valor_engenharia_necessaria',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Valor estimado se ainda não saiu a engenharia', max_digits=12, null=True, verbose_name='Valor da Engenharia Necessária'),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='valor_engenharia_necessaria',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Deixe em branco se ainda não saiu a engenharia (estimativa)', max_digits=12, null=True, verbose_name='Engenharia Necessária'),
        ),
    ]
