# Generated by Django 4.2.27 on 2026-01-09 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contratus', '0003_alter_cliente_options_alter_construtora_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipounidade',
            options={},
        ),
        migrations.AddField(
            model_name='tipounidade',
            name='empreendimento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tipos_unidade', to='contratus.empreendimento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tipounidade',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome do Tipo'),
        ),
        migrations.AlterUniqueTogether(
            name='tipounidade',
            unique_together={('empreendimento', 'nome')},
        ),
    ]
