# Generated by Django 4.2.27 on 2026-01-04 01:49

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contratus', '0003_alter_empreendimento_valor_engenharia_necessaria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='comissao',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='construtora',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='empreendimento',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='historicocontrato',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='unidadeempreendimento',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='TipoUnidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: 2 Quartos, 3 Quartos + Suíte', max_length=200, verbose_name='Nome do Tipo')),
                ('descricao', models.TextField(blank=True, help_text='Descrição detalhada deste tipo de unidade', verbose_name='Descrição')),
                ('quartos', models.IntegerField(default=0, verbose_name='Quartos')),
                ('banheiros', models.IntegerField(default=0, verbose_name='Banheiros')),
                ('vagas_garagem', models.IntegerField(default=0, verbose_name='Vagas de Garagem')),
                ('area_util', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Área Útil (m²)')),
                ('valor_imovel', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor do Imóvel')),
                ('valor_engenharia_necessaria', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True, verbose_name='Valor da Engenharia Necessária')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='tipos_unidade/', verbose_name='Imagem/Planta')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('empreendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_unidade', to='contratus.empreendimento', verbose_name='Empreendimento')),
            ],
            options={
                'verbose_name': 'Tipo de Unidade',
                'verbose_name_plural': 'Tipos de Unidade',
                'ordering': ['nome'],
                'unique_together': {('empreendimento', 'nome')},
            },
        ),
        migrations.AddField(
            model_name='unidadeempreendimento',
            name='tipo_unidade',
            field=models.ForeignKey(blank=True, help_text='Selecione o tipo se esta unidade tiver características específicas', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades', to='contratus.tipounidade', verbose_name='Tipo de Unidade'),
        ),
    ]
