# Generated by Django 4.2.27 on 2026-01-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratus', '0004_alter_tipounidade_options_tipounidade_empreendimento_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipounidade',
            options={'ordering': ['nome'], 'verbose_name': 'Tipo de Unidade', 'verbose_name_plural': 'Tipos de Unidade'},
        ),
        migrations.AddField(
            model_name='tipounidade',
            name='area_util',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='tipounidade',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tipounidade',
            name='banheiros',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tipounidade',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='tipos_unidade/'),
        ),
        migrations.AddField(
            model_name='tipounidade',
            name='quartos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tipounidade',
            name='vagas_garagem',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tipounidade',
            name='valor_engenharia_necessaria',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='tipounidade',
            name='valor_imovel',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=12),
            preserve_default=False,
        ),
    ]
