# Generated by Django 4.2.27 on 2026-01-04 18:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratus', '0004_alter_cliente_id_alter_comissao_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empreendimento',
            name='valor_engenharia_necessaria',
        ),
        migrations.RemoveField(
            model_name='empreendimento',
            name='valor_imovel',
        ),
        migrations.RemoveField(
            model_name='proposta',
            name='valor_parcela',
        ),
        migrations.RemoveField(
            model_name='proposta',
            name='valor_parcelamento_sem_juros',
        ),
        migrations.AddField(
            model_name='proposta',
            name='valor_parcela_cliente',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor que o cliente consegue pagar mensalmente', max_digits=10, verbose_name='Valor da Parcela (que o cliente pode pagar)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposta',
            name='valor_parcelamento_construtora',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor que será pago à construtora (sem juros) - informado pelo corretor', max_digits=12, verbose_name='Parcelamento Construtora (SEM juros)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contrato',
            name='valor_parcelamento',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Parcelamento (SEM juros - para construtora)'),
        ),
        migrations.AlterField(
            model_name='empreendimento',
            name='area_util',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Área Útil (m²) - Padrão'),
        ),
        migrations.AlterField(
            model_name='empreendimento',
            name='banheiros',
            field=models.IntegerField(default=0, verbose_name='Banheiros (Padrão)'),
        ),
        migrations.AlterField(
            model_name='empreendimento',
            name='quartos',
            field=models.IntegerField(default=0, verbose_name='Quartos (Padrão)'),
        ),
        migrations.AlterField(
            model_name='empreendimento',
            name='vagas_garagem',
            field=models.IntegerField(default=0, verbose_name='Vagas de Garagem (Padrão)'),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='numero_parcelas',
            field=models.IntegerField(help_text='Calculado automaticamente: parcelamento_construtora / valor_parcela', verbose_name='Número de Parcelas'),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='valor_engenharia_necessaria',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Deixe em branco se ainda não saiu a engenharia', max_digits=12, null=True, verbose_name='Engenharia Necessária'),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='valor_parcelamento_com_juros',
            field=models.DecimalField(decimal_places=2, help_text='Calculado automaticamente: valor_construtora * 1.5', max_digits=12, verbose_name='Parcelamento com Juros (50% - só para proposta)'),
        ),
        migrations.AlterField(
            model_name='tipounidade',
            name='valor_engenharia_necessaria',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Deixe em branco se ainda não saiu a engenharia', max_digits=12, null=True, verbose_name='Valor da Engenharia Necessária'),
        ),
    ]
