# Generated by Django 4.2.27 on 2026-01-05 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratus', '0005_remove_empreendimento_valor_engenharia_necessaria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empreendimento',
            name='area_util',
        ),
        migrations.RemoveField(
            model_name='empreendimento',
            name='banheiros',
        ),
        migrations.RemoveField(
            model_name='empreendimento',
            name='quartos',
        ),
        migrations.RemoveField(
            model_name='empreendimento',
            name='vagas_garagem',
        ),
        migrations.AlterField(
            model_name='empreendimento',
            name='descricao_completa',
            field=models.TextField(help_text='Descrição geral do empreendimento e suas características comuns', verbose_name='Descrição Completa'),
        ),
    ]
