# Generated by Django 4.2.27 on 2026-01-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratus', '0005_alter_tipounidade_options_tipounidade_area_util_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=200)),
                ('cnpj', models.CharField(max_length=18)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='config/')),
                ('rua', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=20)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Configuração do Sistema',
                'verbose_name_plural': 'Configuração do Sistema',
            },
        ),
    ]
