# Generated by Django 4.2.27 on 2026-01-09 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contratus', '0006_configuracaosistema'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contratus.cliente'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='corretor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contrato',
            name='empreendimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contratus.empreendimento'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='numero_parcelas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contrato',
            name='prorrogacao_dias',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contrato',
            name='unidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contratus.unidadeempreendimento'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='validade_dias',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='contrato',
            name='valor_entrada',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='contrato',
            name='valor_fgts',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='contrato',
            name='valor_financiamento',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='contrato',
            name='valor_imovel',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='contrato',
            name='valor_parcela',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='contrato',
            name='valor_parcelamento',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='contrato',
            name='valor_subsidio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='data_assinatura',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Assinatura'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='data_vencimento_primeira_parcela',
            field=models.DateField(blank=True, null=True, verbose_name='Vencimento 1ª Parcela'),
        ),
    ]
