# Generated by Django 4.2.27 on 2026-01-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratus', '0007_contrato_cliente_contrato_corretor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empreendimento',
            name='cnpj',
            field=models.CharField(default='1', max_length=20),
        ),
    ]
